### ISSUE TITLE
Erreur d'intégration

### ISSUE THREAD

**Issue by hayusama** [jreziga/JRKPaymentSipsBundle#4]
Bonjour,

J'essaye d'implémenter votre module dans mon projet, hors j'ai un petite erreur mais je ne vois pas vraiment d'ou elle vient.
 le fichier : 

> vendor/jrk/paymentsips-bundle/JRK/PaymentSipsBundle/Services/JRKPaymentSips.php

m'indique que $this->datas_request["render"] = $tableau[3]; ne renvoie rien.

Pourriez-vous m'indiquer à quoi correspond l'indice Render du tableau?

**Comment by jr-k** [comment]
Avec quelle module de banque travaillez-vous ? 

Le fonctionnement global du script est assez simple,

```php
$parm = escapeshellcmd($parm); // Correspond aux paramètres à envoyer au binaire 

$result = exec("$path_bin $parm"); // On exécute le binaire avec la chaîne de paramètres construite avec les données de paiement

$tableau = explode("!", "$result"); // Le binaire doit renvoyer une chaîne de paramètre séparée par des "!" comportant au moins 4 valeurs
```

S'il vous manque des valeurs au tableau vérifiez que vous envoyez bien les bons paramètres au binaire
La valeur 3 du tableau (qui équivaut à "render") contient tout le formulaire nécessaire à présenter à l'utilisateur il est donc assez important.

En espérant que ça vous aura éclairé sur le fonctionnement (parfois très sombre) de ce genre de modules de paiement assez vétuste

**Comment by hayusama** [comment]
Autant pour moi j'ai corrigé l'erreur.
Je n'avais pas auto généré le pathfile, je n'avais pas vu votre commande symfony spécifique.
Vous devriez le rajouter dans votre tuto
Sinon super module, ça marche :)

**Comment by jr-k** [comment]
Effectivement je l'avais oublié, la doc était fusionnée avec celle de l'asset install, bizarre, sûrement une mauvaise manipulation.

Content que ça vous plaise :)

**Comment by hayusama** [comment]
J'en profite j'ai du modifier votre fichier ResponseController.
ResponseAction, CancelAction, autoresponseAction
En ajoutant un test :
`public function responseAction(Request $request)
    {
        if($request->getMethod() == 'POST') {
            // Get payment structured data
            $structuredData = $this->getFormattedData($_POST["DATA"]);

            // Add cancel in log file
            $this->addResultInLogFile($structuredData);

            if ($this->hp('jrk_sips_controller_response')) {
                // Add result payment in the request
                $response = $this->forward($this->p("jrk_sips_controller_response"), array('response_data'=>$structuredData));
            } else {
                // Add result payment in the request
                $response = $this->forward($this->routeToControllerName($this->p("jrk_sips_route_response")), array('response_data'=>$structuredData));
            }

            return $response;
        } else {
            return $this->redirectToRoute($this->p("app_route_home"));
        }
    }`

Car lors de la redirection du user après son paiement si le user lance l'url directement il y a une erreur car
$_POST n'existe pas.

On peut également faire 
`jrk_sips_payment_response:
    pattern: /sips_response
    defaults: { _controller: JRKPaymentSipsBundle:Response:response}
    methods : [post]
`
Mais dans ce cas on à pas la redirection mais juste une page erreur
